kind: Pod
apiVersion: v1
metadata:
  name: test-client
spec:
  containers:
    - name: busybox
      image: busybox
      resources:
        requests: # minimum
          cpu: "10m" # 1% of cpu core
          memory: "64M" # 64MB of RAM
        limits: # maximum
          cpu: "100m" # 10% of cpu core
          memory: "256M" # 256MB of RAM
      command:
        - sleep
        - "3600"
      volumeMounts:
        - name: nfs-data
          mountPath: /nfs/data
  volumes:
    - name: nfs-data
      persistentVolumeClaim:
        claimName: test-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-claim
spec:
  storageClassName: nfs-retain # verify storage class
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 100M
