apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      initContainers:
        - name: {{ .Release.Name }}-init
          image: {{ .Values.admin.image }}
          command: ["/bin/chown", "-R", "5050:5050", "/var/lib/pgadmin"] # change owner
          securityContext:
            runAsUser: 0 # root
          volumeMounts:
            - name: var-lib-pgadmin
              mountPath: /var/lib/pgadmin
      containers:
        - name: {{ .Release.Name }}-main
          image: {{ .Values.admin.image }}
          resources:
            requests: # minimum
              cpu: "500m"
              memory: "512M"
            limits: # maximum
              cpu: "1"
              memory: "1G"
          volumeMounts:
            - name: var-lib-pgadmin # external volume
              mountPath: /var/lib/pgadmin # internal volume
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: ADMIN_EMAIL
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: ADMIN_PASSWORD
      volumes:
        - name: var-lib-pgadmin
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-admin