apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: postgres
type: Opaque
data:
  username: {{ default "user" .Values.authentication.username | b64enc | quote }}
  password: {{ default "secret" .Values.authentication.password | b64enc | quote }}

