apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
data:
  ADMIN_EMAIL: {{ .Values.admin.auth.email | b64enc | quote }}
  ADMIN_PASSWORD: {{ .Values.admin.auth.password | b64enc | quote }}
  DATABASE_USER: {{ .Values.database.auth.user | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.database.auth.password | b64enc | quote }}

