apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-admin
spec:
  selector:
    app: admin
  ports:
    - port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-database
spec:
  selector:
    app: database
  ports:
    - port: 5432
