apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    app: database
spec:
  serviceName: "postgresql"
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.database.image }}
          resources:
            requests: # minimum
              cpu: "500m"
              memory: "1G"
            limits: # maximum
              cpu: "1"
              memory: "2G"
          volumeMounts:
            - name: var-lib-postgres-data # external volume
              mountPath: /var/lib/postgres/data # internal volume
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: DATABASE_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: DATABASE_PASSWORD
  volumeClaimTemplates:
    - metadata:
        name: var-lib-postgres-data
      spec:
        storageClassName: {{ .Values.database.storage }}
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 1G
        selector:
          matchLabels:
            app: database
