apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-admin
  labels:
    app: admin
spec:
  storageClassName: standard # default storage
  persistentVolumeReclaimPolicy: Retain
  accessModes: [ "ReadWriteMany" ]
  capacity:
    storage: 1G
  hostPath:
    path: /opt/kubernetes/{{ .Release.Name }}/admin
    type: DirectoryOrCreate # create if not exist
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-database
  labels:
    app: database
spec:
  storageClassName: standard # default storage
  persistentVolumeReclaimPolicy: Retain
  accessModes: [ "ReadWriteMany" ]
  capacity:
    storage: 1G
  hostPath:
    path: /opt/kubernetes/{{ .Release.Name }}/database
    type: DirectoryOrCreate # create if not exist