apiVersion: v2
name: nfsserver
type: application
version: 0.1.0
appVersion: "2.6.2"
description: A Helm chart for Kubernetes
icon: icon.svg
maintainers:
    - email: thiago@thau.tech
      name: Thiago Madureira Braga
