apiVersion: v2
name: nfsserver
type: application
version: 0.1.0 # chart version
appVersion: "2.6.2" # bundle version
description: NFS Server Helm Chart for Kubernetes
icon: icon.svg
maintainers:
    - email: thiago@thau.tech
      name: Thiago Madureira Braga
