apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
spec:
  storageClassName: {{ .Values.storage }}
  accessModes: [ "ReadWriteMany" ]
  resources:
      requests:
          storage: 1G