apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-claim
  labels:
    app: jupyter
spec:
  storageClassName: {{ .Values.storage.class }}
  accessModes: [ "ReadWriteMany" ]
  resources:
      requests:
          storage: 1G