apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: jupyter
spec:
  selector:
    app: jupyter
  ports:
    - name: lab
      port: 8888
    - name: spark
      port: 4040