apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Release.Name }}-claim
    labels:
        app: postgresql
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 8G
