apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-service
    labels:
        app: postgresql
spec:
    type: NodePort
    ports:
        - port: 5432
    selector:
        app: postgresql
