apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ .Release.Name }}-volume
    labels:
        app: postgresql
        type: local
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteMany
    capacity:
        storage: 8G
    hostPath:
        path: "/opt/kubernetes/{{ .Release.Name }}/data"
