apiVersion: v2
name: postgresql
type: application
version: 0.1.0 # chart version
appVersion: "16.0" # bundle version
description: PostgreSQL Helm Chart for Kubernetes
icon: icon.svg
maintainers:
    - email: thiago@thau.tech
      name: Thiago Madureira Braga
