apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      initContainers:
        - name: {{ .Release.Name }}-container-init
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ["/bin/chown", "-R", "5050:5050", "/var/lib/pgadmin"] # change owner
          securityContext:
            runAsUser: 0 # root
          volumeMounts:
            - name: var-lib-pgadmin
              mountPath: /var/lib/pgadmin
      containers:
        - name: {{ .Release.Name }}-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          resources:
            requests: # usual resources
              cpu: "500m" # half of cpu core
              memory: "512M" # 512MB of RAM
            limits: # max resources
              cpu: "1" # one cpu core
              memory: "1G" # 1GB of RAM
          volumeMounts:
            - name: var-lib-pgadmin # external volume
              mountPath: /var/lib/pgadmin # internal volume
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: email
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: password
      volumes:
        - name: var-lib-pgadmin
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-claim