apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}
  labels:
    app: pgadmin
spec:
  storageClassName: standard # default storage
  persistentVolumeReclaimPolicy: Delete
  accessModes: [ "ReadWriteMany" ]
  capacity:
    storage: 1G
  hostPath:
    path: /opt/kubernetes/{{ .Release.Name }}
    type: DirectoryOrCreate # create if not exist