apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-volume
  labels:
    app: pgadmin
spec:
  storageClassName: manual # default storage
  accessModes: [ "ReadWriteMany" ]
  capacity:
    storage: 1G
  hostPath:
    path: "/opt/kubernetes/{{ .Release.Name }}/volume"
    type: DirectoryOrCreate # create if not exist