apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.host.name }}
    http:
      paths:
      - path: {{ .Values.host.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 9090