apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    app: storage
spec:
  serviceName: "minio-storage"
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image }}
          resources:
            requests: # minimum
              cpu: "500m"
              memory: "512M"
            limits: # maximum
              cpu: "1"
              memory: "1G"
          command: [minio, server, /var/lib/minio/data, --console-address, ":9090"]
          volumeMounts:
            - name: var-lib-minio-data # external volume
              mountPath: /var/lib/minio/data # internal volume
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: PASSWORD
  volumeClaimTemplates:
    - metadata:
        name: var-lib-minio-data
      spec:
        storageClassName: {{ .Values.storage }}
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 1G
