apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: server
spec:
  type: ClusterIP # default and internal service type
  clusterIP: {{ .Values.address }} # static internal address
  selector:
    app: server
  ports:
    - name: nfs
      port: 2049
    # - name: mountd
    #   port: 20048
    # - name: rpcbind
    #   port: 111
