apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: ClusterIP # default and internal service type
  clusterIP: {{ .Values.service.address }} # static internal address
  selector:
    app: nfs
  ports:
    - name: nfs
      port: 2049
