apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-statefulset
spec:
  serviceName: "network-file-system"
  replicas: 1
  selector:
    matchLabels:
      app: nfs
  template:
    metadata:
      labels:
        app: nfs
    spec:
      containers:
        - name: {{ .Release.Name }}-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          resources:
            requests: # usual resources
              cpu: "500m" # half of cpu core
              memory: "512M" # 512MB of RAM
            limits: # max resources
              cpu: "1" # one cpu core
              memory: "1G" # 1GB of RAM
          securityContext:
            privileged: true
          volumeMounts:
            - name: exports
              mountPath: /exports
          ports:
            - name: nfs
              containerPort: 2049
            #   - name: mountd
            #       containerPort: 20048
            #   - name: rpcbind
            #       containerPort: 111
  volumeClaimTemplates:
    - metadata:
        name: exports
      spec:
        storageClassName: {{ .Release.Name }}-storage
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 10G