apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  serviceName: "network-file-system"
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image }}
          resources:
            requests: # minimum
              cpu: "500m"
              memory: "512M"
            limits: # maximum
              cpu: "1"
              memory: "1G"
          securityContext:
            privileged: true
          volumeMounts:
            - name: exports
              mountPath: /exports
  volumeClaimTemplates:
    - metadata:
        name: exports
      spec:
        storageClassName: {{ .Values.storage }}
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 10G