apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-volume
  labels:
    app: networkfilesystem
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/kubernetes/{{ .Release.Name }}/volume
    type: DirectoryOrCreate # create if not exist
